name: search_highlight_text
description: Simple Inherited Widget to highlight text in a search result, with custom highlight Color and highlight TextStyle.
version: 1.0.0+1
homepage: https://github.com/omarfaroke/search_highlight_text

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
